### ISSUE TITLE
Why do you know that the precision of my cifar100 is higher than the data in the form

### ISSUE THREAD

**Issue by wcc150491** [zgcr/SimpleAICV_pytorch_training_examples_on_ImageNet_COCO_ADE20K#29]
<img width="509" alt="image" src="https://user-images.githubusercontent.com/76274477/220930259-679d6c32-ee9c-4f76-8e67-48cf79c67cd5.png">

**Comment by zgcr** [comment]
> <img alt="image" width="509" src="https://user-images.githubusercontent.com/76274477/220930259-679d6c32-ee9c-4f76-8e67-48cf79c67cd5.png">

hi，if you want to check train and test log,just run train.sh and test.sh,then check train.log and test.log file.
For example,if you want to train and test resnet50cifar, enter classification_training/cifar100/resnet50cifar,adjust setting in train_config.py and test_config.py,then run train.sh and test.sh.You will find a log directory in this directory,and a new rain.log and test.log file will be generated.

**Comment by zgcr** [comment]
> <img alt="image" width="509" src="https://user-images.githubusercontent.com/76274477/220930259-679d6c32-ee9c-4f76-8e67-48cf79c67cd5.png">

train log and test log file will be update when you start train.sh and test.sh.
